"""add meta to interview question

Revision ID: 10f2ca810e3b
Revises: 83d57f70c081
Create Date: 2026-06-26 12:34:05.684800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f2ca810e3b'
down_revision: Union[str, None] = '83d57f70c081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('meta', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_questions', 'meta')
    # ### end Alembic commands ###
