"""add email verification and password reset fields

Revision ID: 6c59815ab5f0
Revises: 0d5acab76a9e
Create Date: 2026-03-12 16:43:07.559509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c59815ab5f0'
down_revision: Union[str, None] = '0d5acab76a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('verification_code_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('reset_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('reset_code_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_code_expires')
    op.drop_column('users', 'reset_code')
    op.drop_column('users', 'verification_code_expires')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###
