"""add access_token to interview

Revision ID: d8bdee2aaf77
Revises: 10f2ca810e3b
Create Date: 2026-06-26 12:41:58.911820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8bdee2aaf77'
down_revision: Union[str, None] = '10f2ca810e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('access_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_interviews_access_token'), 'interviews', ['access_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interviews_access_token'), table_name='interviews')
    op.drop_column('interviews', 'access_token')
    # ### end Alembic commands ###
