"""add users cv_documents job_offers matches tables

Revision ID: ee370044acc8
Revises: 87ddcf8e3163
Create Date: 2026-02-26 16:52:45.074221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee370044acc8'
down_revision: Union[str, None] = '87ddcf8e3163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('recruteur', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cv_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'extracted', 'parsed', 'error', name='cvstatus'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_documents_candidate_id'), 'cv_documents', ['candidate_id'], unique=False)
    op.create_table('job_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=True),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('competences_requises', sa.JSON(), nullable=True),
    sa.Column('localisation', sa.String(length=255), nullable=True),
    sa.Column('type_contrat', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('active', 'closed', 'draft', name='jobstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_offers_recruiter_id'), 'job_offers', ['recruiter_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_offer_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'reviewed', 'accepted', 'rejected', name='matchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_offer_id'], ['job_offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_candidate_id'), 'matches', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_matches_job_offer_id'), 'matches', ['job_offer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_job_offer_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_candidate_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_job_offers_recruiter_id'), table_name='job_offers')
    op.drop_table('job_offers')
    op.drop_index(op.f('ix_cv_documents_candidate_id'), table_name='cv_documents')
    op.drop_table('cv_documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
